### ISSUE TITLE
侧边栏图标bug

### ISSUE THREAD

**Issue by iAmP1us** [MapleRecall/LiteLoaderQQNT-CCND#2]
装了Scriptio里的to-contact-list-top和LiteLoaderQQNT-CCND，同时启动的时候，CCND的侧边栏图标会变成to-contact-list-top的一样的icon。
![sidebar](https://github.com/user-attachments/assets/51eeee2e-ad4a-411e-80f2-318d54a8b6ec)

**Comment by MapleRecall** [comment]
修了，但是图标顺序得`to-contact-list-top`自己去处理
