### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by rhwong** [MapleRecall/LiteLoaderQQNT-CCND#3]
高斯模糊对单位发的办公本来说好像有点吃力，有没有可能有一个低配置开关，将头像和聊天内容部分做成无害图片直接替换呢？

**Comment by rhwong** [comment]
我这个1165G7的商务本，开启插件后QQ能吃到30%的CPU，并且会发生一些奇妙的卡顿。

**Comment by MapleRecall** [comment]
0.1.4加了，可以试试

**Comment by rhwong** [comment]
感谢！让我来试试。^^
