### ISSUE TITLE
重新启动后无法正确显示

### ISSUE THREAD

**Issue by dale003** [MapleRecall/LiteLoaderQQNT-CCND#4]
问题1：每次重新启动QQ登陆后，不管鼠标移动到具体的消息，还是联系人列表，都只能显示鼠标准确指示的那个信息和群组名称；只能在设置中重新打开关闭----全局开关，才能准确显示。
![Snipaste_2024-08-09_09-58-49](https://github.com/user-attachments/assets/8404a96b-be51-4d3b-a96d-60e048c78122)
![Snipaste_2024-08-09_09-59-01](https://github.com/user-attachments/assets/cda3d1a9-ad6d-4f16-a286-316e5f907652)
问题2：主界面中的全局开关“小人标志”只成功显示一次，后面就一直没有了，
![Snipaste_2024-08-09_09-57-14](https://github.com/user-attachments/assets/a6d868b0-621d-4da4-a487-58c088bd70ee)
![Snipaste_2024-08-09_10-04-38](https://github.com/user-attachments/assets/0c58ab95-d232-4426-b46e-8fea6c1a3e1f)

**Comment by MapleRecall** [comment]
第一个问题确实有问题，第二个我得找找看是啥原因
