### ISSUE TITLE
细节问题

### ISSUE THREAD

**Issue by SEVEN-6174** [MapleRecall/LiteLoaderQQNT-CCND#5]
好友通知和群通知在主面板不会被隐藏,分组的人数数字正常显示
![image](https://github.com/user-attachments/assets/3007b091-851f-436f-ae71-ea265815cf3c)
还有就是好友通知和群通知点进去的标题在鼠标移上去不会恢复正常
概览窗口为关闭

**Comment by MapleRecall** [comment]
“好友通知”和“群通知”这个是设计如此的，因为最初目标就是会尽量不影响不涉及实际信息的界面元素。
下面的移上去恢复确实没加，会改一下。
